#ifndef IDENTIFIERS_H
#define IDENTIFIERS_H

typedef enum {
    MsgIO = 1,
    MsgManual = 2,
    MsgMode = 3,
    MsgTimer = 4,
    MsgCounter = 5,
    MsgPoint = 6,
    MsgAlerm = 7,
    MsgError = 8,
    MsgOperation = 9,
    MsgSystem = 10,
    MsgHelp = 11,
    MsgTopTab = 20,
    MsgBottomTab = 21,
    MsgAxisName = 22,
    MsgUnit = 23,
    MsgOriginPane = 30,
    MsgManualPage = 31,
    MsgAutoPage = 32,
    MsgMenu = 33,
} MessageGroupId;

typedef enum {
    ModCommon = 1,
    ModMode = 2,
    ModTimer = 3,
    ModCounter = 4,
    ModProgram = 5,
    ModOperation = 6,
    ModAxisP1PM = 7,
    ModAxisP1VM = 8,
    ModAxisP2PM = 9,
    ModAxisP2VM = 10,
    ModAxisP3PM = 11,
    ModAxisP3VM = 12,
    ModAxisP4PM = 13,
    ModAxisP4VM = 14,
    ModAxisP5PM = 15,
    ModAxisP5VM = 16,
    ModAxisP1PS = 17,
    ModAxisP1VS = 18,
    ModAxisP2PS = 19,
    ModAxisP2VS = 20,
    ModAxisP3PS = 21,
    ModAxisP3VS = 22,
    ModAxisP4PS = 23,
    ModAxisP4VS = 24,
    ModAxisP5PS = 25,
    ModAxisP5VS = 26,
    ModStdPalletize1 = 27,
    ModStdPalletize2 = 28,
    ModStdPalletize3 = 29,
    ModStdPalletize4 = 30,
    ModStdPalletize5 = 31,
    ModStdPalletize6 = 32,
    ModStdPalletize7 = 33,
    ModStdPalletize8 = 34,
    ModOpenPalletize1 = 35,
    ModOpenPalletize2 = 36,
    ModOpenPalletize3 = 37,
    ModOpenPalletize4 = 38,
    ModOpenPalletize5 = 39,
    ModOpenPalletize6 = 40,
    ModOpenPalletize7 = 41,
    ModOpenPalletize8 = 42,
    ModPathSetting = 43,
    ModAccelSetting = 44,
    ModActuatorSetting = 45,
    ModMechanicalParam1 = 46,
    ModMechanicalParam2 = 47,
    ModMechanicalParam3 = 48,
    ModAmpParam1 = 49,
    ModAmpParam2 = 50,
    ModAmpParam3 = 51,
    ModAmpParam4 = 52,
    ModAmpParam5 = 53,
    ModVersion = 54,
    ModController = 55,
    ModCNTDirectory = 56,
    ModAllAxisesAmpMonitor = 57,
    Mod1AxisAmpMonitor = 58,
    Mod3AxisesAmpMonitor = 59,
    ModInputControll1 = 60,
    ModInputControll2 = 61,
    ModIODetail = 62,

} ModBusGroupId;

typedef enum {
    PenCommon = 1,
    PenAlerm = 2,
    PenAlert = 3,
    PenAction = 4,
    PenOrignate = 5,
    PenManual = 6,
    PenAuto = 7,
    PenMenu = 8,

    PenSelectFunction = 10,
    PenTimer = 11,
    PenStandardPoint = 12,
    PenStandardPalletize = 13,
    PenOpenPalletize = 14,
    PenEditProgram = 15,
    PenPath = 16,
    PenAccelerate = 17,
    PenActuator = 18,
    PenMechancalConstant = 19,
    PenAmpParameter = 20,
    PenController = 21,
    PenExternalMemory = 22,
    PenAmpMonitor = 23,
    PenIOControl = 24,

    PenIODisplay = 26,
    PenAlertHistory = 27,
    PenOperationHistory = 28,
    PenIOHistory = 29,
} PenGroupId;

#endif // IDENTIFIERS_H
